name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Symfony CLI
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          export PATH="$HOME/.symfony/bin:$PATH"
          symfony -V
